### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sfan5** [minetest/irrlicht#107]
IrrlichtMt is meant to be copied into Minetest some day, ideally at a point where we can throw away much of the code because we would use SDL2 + our own OpenGL(ES) renderer by that point.

This issue collects things that should be done to the Irrlicht source in any case before that:
* [x] Unbundle libraries
* [x] Replace build system with CMake
* [x] Drop DirectX, software drivers and unused file formats
* [x] Drop other features we don't use
* [ ] Try to identify long outdated code and fix it (ancient Windows/OSX, other API/compiler support or workarounds and similar things)
* Get rid of non-STL containers and types:
* [x] + `core::map`
* [ ] + `core::array`
* [ ] + `core::list`
* [ ] + `core::string`
* [ ] Overhaul `std::ustring` (`std::wstring` wouldn't work as replacement)
* [ ] ...

**Comment by rubenwardy** [comment]
Shouldn't improving SDL support and removing other drivers be in this list?

**Comment by sfan5** [comment]
Added.

**Comment by JosiahWI** [comment]
Minetest does version checking on IrrlichtMt when it calls find_package, but I reckon that isn't being updated on either end to make sure it actually checks for the right version requirements. I got a segfault compiling with the wrong IrrlichtMt/Minetest pair earlier.

**Comment by oong819** [comment]
will OGLES 2 have dynamic shadow in future?

**Comment by rubenwardy** [comment]
Wrong repo and issue, see https://github.com/minetest/minetest/issues/11339

**Comment by Starconstructor** [comment]
Would it be possible to port over Vulkan into this fork? I'd do it myself, but I have a skill issue. [Someone else](https://github.com/JayDT/Irrlicht) made a Vulkan-supported Irrlicht fork, maybe their code could be brought over here?

**Comment by sfan5** [comment]
Technically possible, maybe.
However if you're thinking of performance improvements or better effects there is *a lot* of room for improvement if Minetest used OpenGL more effectively / to its full potential. Time is better spent on that instead of a new rendering backend.

**Comment by numberZero** [comment]
> Try to identify long outdated code and fix it (ancient Windows/OSX, other API/compiler support or workarounds and similar things)

See #157 and #158. Also, #160 but that one may deserve its own item.

**Comment by sfan5** [comment]
> I plan to do #158 and then #160. @sfan5 is that OK?

Of course.

**Comment by x2048** [comment]
If we want to implement normal mapping at some point (e.g. for PBR/detailed reflections/light), we will need vertex tangents from what I know.

**Comment by sfan5** [comment]
I'll cross that off the list then.

**Comment by x2048** [comment]
> What’s about fully custom vertex types? 

That would be amazing.

**Comment by midn1** [comment]
Do I understand correctly that old hardware support is intended to be dropped?

**Comment by sfan5** [comment]
What are you thinking of when saying "old hardware"?

**Comment by midn1** [comment]
That answers my question, thanks.
